name: push dockerhub

on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.lock'
      - '**.yaml'
      - 'Dockerfile'
      - 'crates/mdbx-remote/mdbx-sys/libmdbx/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull sources'
        uses: actions/checkout@v4

      - name: 'Set up Rust'
        uses: dtolnay/rust-toolchain@stable

      - name: 'Setup libclang'
        run: sudo apt update && sudo apt install -y libclang-dev
      
      - name: 'Test'
        timeout-minutes: 5
        run: cargo test
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MDBX_DOCKERHUB_USERNAME }}
          password: ${{ secrets.MDBX_DOCKERHUB }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: lazymio/mdbx-remote:latest